name: apple-refund-assistant-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker test image
      run: docker build --build-arg BUILD_MODE=test -t apple-refund-assistant-test .
    
    - name: Create coverage directory
      run: mkdir -p coverage
    
    - name: Start test container
      run: |
        docker run -d \
          --name test-container \
          -e DB_CONNECTION=sqlite \
          -e DB_DATABASE=database/database.sqlite \
          -e APP_ENV=testing \
          apple-refund-assistant-test
    
    - name: Setup test environment
      run: |
        echo "Setting up test environment..."
        docker exec test-container cp .env.example .env
        docker exec test-container composer install
        docker exec test-container php artisan key:generate
        docker exec test-container mkdir -p database
        docker exec test-container touch database/database.sqlite
    
    - name: Run tests with coverage
      run: |
        echo "Running tests with coverage..."
        docker exec test-container php artisan test --coverage --coverage-xml coverage/coverage.xml
    
    - name: Copy coverage files from container
      run: |
        docker cp test-container:/var/www/html/coverage ./
        echo "Coverage files copied successfully"
    - name: Remove test container
      run: docker rm -f test-container
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverage/coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        