name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker test image
      run: docker build -t apple-refund-assistant-image .
    
    - name: Run tests in Docker container
      run: |
        docker run --rm \
          --user root \
          -e DB_CONNECTION=sqlite \
          -e DB_DATABASE=database/database.sqlite \
          -e APP_ENV=testing \
          apple-refund-assistant-image \
          sh -c "
            echo 'Installing coverage driver...' &&
            install-php-extensions pcov &&
            echo 'Switching to www-data user and running tests...' &&
            su www-data -s /bin/sh -c '
              cd /var/www/html &&
              echo \"Installing dev dependencies...\" &&
              composer install --optimize-autoloader &&
              cp .env.example .env &&
              php artisan key:generate &&
              mkdir -p database &&
              touch database/database.sqlite &&
              echo \"Running tests with coverage...\" &&
              php artisan test --coverage-xml=coverage
            '
          "
    - name: Upload coverage reports to Codecov
      if: ${{ !env.ACT }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false